### ISSUE TITLE
bug: ignore getter, if no setter with the same name is available

### ISSUE THREAD

**Issue by lukas-h** [dartclub/firestore_dart#21]

**Comment by jeromoney** [comment]
I found that @FirestoreAttribute(ignore: true) has no effect on getters. The two work arounds that I found were: a) switching the getter to a method. b) swallowing these getters in the default constructor by adding an identically named variable that does nothing. The second method has the unfortunate side-affect of littering your Firestore database with some unnecessary data, such as a hash code method that you overrode.
