### ISSUE TITLE
[firestore_serialize] example crashes on null

### ISSUE THREAD

**Issue by ciriousjoker** [dartclub/firestore_dart#37]
### Proposal:

Change factories to this:

```
factory Model.fromMap(Map<String, dynamic> data) =>
      data != null ? _$modelFromMap(data) : null;
```

**Comment by lukas-h** [comment]
What I can see is, that this proposal does not effect the serialization, but on how you are using the generated methods.

**Comment by ciriousjoker** [comment]
What I meant was to include this check in the deserialization function itself so the factory doesn't have to check it. The wording was bad though

**Comment by lukas-h** [comment]
@CiriousJoker, you now have the possibility to add  the attribute `nullable` to the annotation.

```dart
@FirestoreDocument(nullable: true)
```

if it is set `true`, it has the proposed null check.

If it's `false`, an AssertionError is thrown during development.

**Comment by ciriousjoker** [comment]
Perfect!

**Comment by ciriousjoker** [comment]
the nullable flag seems to only work for the whole document though, so this:

```
  @FirestoreAttribute(nullable: true)
  List<String> myList;
```

does not work sadly.
