### ISSUE TITLE
[firestore_serialize] List<String> can't be converted

### ISSUE THREAD

**Issue by ciriousjoker** [dartclub/firestore_dart#38]
### Error
`'List<dynamic>' is not a subtype of type 'List<String>'`

### Workaround for now
 ```
  Model({
    this.selfRef,
    List tags,
  }) {
    this.tags = tags.cast<String>();
  }
```

**Comment by lukas-h** [comment]
Let me investigate that
 
Is the type `<String>` annotated for the class member?

**Comment by lukas-h** [comment]
I will prepare a new release
