### ISSUE TITLE
[firestore_serialize] Support for Timestamps

### ISSUE THREAD

**Issue by ciriousjoker** [dartclub/firestore_dart#39]
You added support in 724a838f1444eca5cf237ec53d61cd1b4bd7cae7, but removed it again in d5282b1ac9436a229435393bce18c4dfdf4486e2 with the intention to improve compatibility with firebase_api and better generated output.

I'm using [cloud_firestore](https://pub.dev/packages/cloud_firestore) and according to [this](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/CHANGELOG.md#0130) item in the changelog, Timestamp seems to be the preferred way (in general though, not just that library).

**Comment by lukas-h** [comment]
This package is intended to be used together with https://github.com/dartclub/firestore_dart/tree/master/firestore_api, which converts Timestamp to DateTime

**Comment by ciriousjoker** [comment]
That's really unfortunate because I can't write an easy workaround for the onSnapshot function as I did with onMap.

What was the issue though? Adding another Datatype for compatibility with other libraries doesn't reduce the compatibility with that one. And the generated output doesn't seem to get convoluted too much since you can just pass on the Timestamp as is without touching it

**Comment by lukas-h** [comment]
@CiriousJoker support added

**Comment by ciriousjoker** [comment]
Thank's a lot!
